apiVersion: v1
kind: Secret
metadata:
  name: webserver
type: Opaque
data:
  username: {{ .Values.airflow.webserver.username | b64enc | quote}}
  password:  {{ .Values.airflow.webserver.password | b64enc | quote }}
  secret_key: {{ .Values.airflow.webserver.secret_key | b64enc | quote }}