FROM apache/airflow:2.7.3-python3.9 as build

USER root
RUN apt-get install -y apt-transport-https
RUN apt-get autoremove -yqq --purge
RUN apt-get clean
RUN apt-get -y update
RUN apt-get install -y default-libmysqlclient-dev
RUN apt-get install -y gcc
RUN sudo apt install -y pkg-config
RUN sudo pip install mysqlclient

COPY trainer/requirements-airflow.txt .
COPY .env.k8s .env
RUN pip3 install -r requirements-airflow.txt; pip3 install python-decouple


USER airflow
RUN pip3 install -r requirements-airflow.txt; pip3 install python-decouple

USER airflow
COPY --chown=airflow:root trainer/dags /opt/airflow/dags
