apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.host }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mysql-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      restartPolicy: Always
      # prevent chown running in startup script
      securityContext:
        runAsUser: 999
      containers:
        # v8 required extra libraries to be installed in airflow images for authentication
        - image: mysql
          name: mysql-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          args: ["--tmpdir", "/tmp", "--explicit_defaults_for_timestamp"]
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: username
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
